-- Run this script in Supabase SQL Editor before enabling cloud progress sync.
create table if not exists public.learning_progress (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    card_key text not null,
    lesson text not null,
    hanzi text not null,
    review_count integer not null default 0,
    last_reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    unique (user_id, card_key)
);

create table if not exists public.quiz_results (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    question_count integer not null,
    score integer not null,
    lesson_ids jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.learning_progress enable row level security;
alter table public.quiz_results enable row level security;

drop policy if exists "Users can read their learning progress" on public.learning_progress;
create policy "Users can read their learning progress" on public.learning_progress for select using (auth.uid() = user_id);
drop policy if exists "Users can insert their learning progress" on public.learning_progress;
create policy "Users can insert their learning progress" on public.learning_progress for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update their learning progress" on public.learning_progress;
create policy "Users can update their learning progress" on public.learning_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can read their quiz results" on public.quiz_results;
create policy "Users can read their quiz results" on public.quiz_results for select using (auth.uid() = user_id);
drop policy if exists "Users can insert their quiz results" on public.quiz_results;
create policy "Users can insert their quiz results" on public.quiz_results for insert with check (auth.uid() = user_id);
